' The diagram uses PlantUML. A picture will always be saved with the same name.
' Please note that this is a conceptual model, implementation may differ. For
' example: I won't really create a class called Request, I'll just use objects.
' Also, not reviewed yet.
@startuml
  title Class Diagram. Doesn't have to represent actual truth!
  Request <|-- GETRequest
  Request <|-- POSTRequest
  RequestRunner --> "0..*" Request : at any times contains
  PhaseRunner --> "0..*" Phase : has
  Phase --> PhaseState : has
  Phase <|-- Logout
  Phase <|-- Login
  Phase <|-- GetYears
  Phase <|-- ScrapeGrades
  Logout ..> Login : prepares data for
  Login ..> GetYears : prepares data for
  GetYears ..> ScrapeGrades : prepares data for
  abstract class Request {
    +url:String
    +handler:Function
    +infoForHandler:String
  }
  class GETRequest {
  }
  class POSTRequest {
    +nameValuePairs:Array[pairsCount][2]
  }
  class RequestRunner {
    #delay:Number
    #requestQ:Request[]
    #interval:Interval
    +RequestRunner(delay:Number)
    +void changeDelay(delay:Number)
    +void emptyQueue()
    +void addRequestToQueue(request:Request)
    #applyRequest(request:Request)
  }
  abstract class Phase {
    #prevResult:Result
' Should be Function(Result) but PlantUML would consider it a function
    #callback:Function
    #state:PhaseState
    #result:Result
    +Phase(prevResult:Result)
    +setCallback(callback:Function(Result))
    +void start()
    #void finish()
  }
  class Logout {
    ..Needs no data at all..
    +Logout(prevResult:Result)
    #logoutHandler(xhr)
  }
  note bottom of Logout : Only class that does the work even if err.length > 0.
  class Login {
    ..{user, pass}..
    +Login(prevResult:Result)
    #loginHandler(xhr)
  }
  class GetYears {
    ..Assumes logged in..
    ..{user}..
    #termsCount:Int
    #years:String Array[3][]
    +GetYears(prevResult:Result)
    #getYearsHandler(xhr)
    ..result:years:String Array[3][]..
    ..Example: [['12', '11'], [], ['10']]..
  }
  class ScrapeGrades {
    ..Assumes logged in..
    ..{user, years:String Array[3][]}..
    #termsYearsCount:Int[3]
    #doneTermsYearsCount:Int[3]
    +ScrapeGrades(prevResult:Result)
    #scrapeTermHandler(xhr)
    ..result:{0..*String:Array[3] each either HTML Table or undefined}..
    ..Example: {'12':[HT, undefined, HT], '10':[HT, HT, HT]}..
  }
  enum PhaseState {
    +NotStartedYet
    +Done
  }
  class PhaseRunner {
    #phases:Phase[]
    #someInput:Result
' Should be Function(Result) but PlantUML would consider it a function
    #callback:Function
    #currentIndex:Int
    +PhaseRunner(phases:Phase[], someInput:Result, callback:Function(Result))
    +void start()
    +void stopAndCallCallback()
' Will be curried with index
    #phaseCallback(index, Result)
  }
  note top of PhaseRunner : PhaseRunner is a Singleton. No impl. details here.
  class Result {
    +err:Error[]
    +user:String, for checking on most pages
  }
  class Utilities {
    +void sendGET(url:String, handler:Function, infoForHandler:Object)
    +void sendPOST(url:String, nameValuePairs:Array[][2], handler:Function,
              infoForHandler:Object)
    +DOMObject parseHTML(anHTMLString:String)
    +Bool/String checkUser(user:String, doc:DOMObject)
    +Function curryOneParam(fn:Function, param:var)
    +Bool/DOMObject handlerBase(xhr)
    #void initReq(url:String, handler:Function, infoForHandler:Object)
  }
@enduml
